---
version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      TZ: Europe/London
      WATCHTOWER_SCHEDULE: "00 35 03 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
